CREATE TABLE juz_names (id int(3) NOT NULL PRIMARY KEY, name text NOT NULL, tname text NOT NULL);

INSERT INTO juz_names (id,name,tname) VALUES (1, "الم", "Alif Lam Meem");
INSERT INTO juz_names (id,name,tname) VALUES (2, "سَيَقُولُ", "Sayaqool");
INSERT INTO juz_names (id,name,tname) VALUES (3, "تِلْكَ الرُّسُلُ", "Tilkal Rusull");
INSERT INTO juz_names (id,name,tname) VALUES (4, "لَنْ تَنَالُوا", "Lan Tana Loo");
INSERT INTO juz_names (id,name,tname) VALUES (5, "وَالْمُحْصَنَاتُ", "Wal Mohsanat");
INSERT INTO juz_names (id,name,tname) VALUES (6, "لَا يُحِبُّ اللَّهُ", "La Yuhibbullah");
INSERT INTO juz_names (id,name,tname) VALUES (7, "وَإِذَا سَمِعُوا", "Wa Iza Samiu");
INSERT INTO juz_names (id,name,tname) VALUES (8, "وَلَوْ أَنَّنَا", "Wa Lau Annana");
INSERT INTO juz_names (id,name,tname) VALUES (9, "قَالَ الْمَلَأُ", "Qalal Malao");
INSERT INTO juz_names (id,name,tname) VALUES (10, "وَاعْلَمُوا", "Wa A'lamu");
INSERT INTO juz_names (id,name,tname) VALUES (11, "يَعْتَذِرُونَ", "Yatazeroon");
INSERT INTO juz_names (id,name,tname) VALUES (12, "وَمَا مِنْ دَابَّةٍ", "Wa Mamin Da'abat");
INSERT INTO juz_names (id,name,tname) VALUES (13, "وَمَا أُبَرِّئُ", "Wa Ma Ubrioo");
INSERT INTO juz_names (id,name,tname) VALUES (14, "رُبَمَا", "Rubama");
INSERT INTO juz_names (id,name,tname) VALUES (15, "سُبْحَانَ الَّذِي", "Subhanallazi");
INSERT INTO juz_names (id,name,tname) VALUES (16, "قَالَ أَلَمْ", "Qal Alam");
INSERT INTO juz_names (id,name,tname) VALUES (17, "اقْتَرَبَ", "Aqtarabo");
INSERT INTO juz_names (id,name,tname) VALUES (18, "قَدْ أَفْلَحَ", "Qadd Aflaha");
INSERT INTO juz_names (id,name,tname) VALUES (19, "وَقَالَ الَّذِينَ", "Wa Qalallazina");
INSERT INTO juz_names (id,name,tname) VALUES (20, "أَمَّنْ خَلَقَ", "A'man Khalaq");
INSERT INTO juz_names (id,name,tname) VALUES (21, "اتْلُ مَا أُوحِيَ", "Utlu Ma Oohi");
INSERT INTO juz_names (id,name,tname) VALUES (22, "وَمَنْ يَقْنُتْ", "Wa Manyaqnut");
INSERT INTO juz_names (id,name,tname) VALUES (23, "وَمَا لِيَ", "Wa Mali");
INSERT INTO juz_names (id,name,tname) VALUES (24, "فَمَنْ أَظْلَمُ", "Faman Azlam");
INSERT INTO juz_names (id,name,tname) VALUES (25, "إِلَيْهِ يُرَدُّ", "Elahe Yuruddo");
INSERT INTO juz_names (id,name,tname) VALUES (26, "حم", "Ha'a Meem");
INSERT INTO juz_names (id,name,tname) VALUES (27, "قَالَ فَمَا خَطْبُكُمْ", "Qala Fama Khatbukum");
INSERT INTO juz_names (id,name,tname) VALUES (28, "قَدْ سَمِعَ اللَّهُ", "Qadd Sami Allah");
INSERT INTO juz_names (id,name,tname) VALUES (29, "تَبَارَكَ الَّذِي", "Tabarakallazi");
INSERT INTO juz_names (id,name,tname) VALUES (30, "عَمَّ يَتَسَاءَلُونَ ", "Amma Yatasa'aloon");

